---
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - dev
  variables:
    GIT_REMOTE_URL: ssh://dokku@kevinanatole.uk:22/thathrow-backend
  script:
    - dokku-deploy
  after_script:
    - dokku-unlock
