# For more information: https://laravel.com/docs/sail
version: "3"
services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.0/app
    ports:
      - "${APP_PORT:-80}:80"
      - "8080:8080"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - selenium
  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "sailmysql:/var/lib/mysql"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sailredis:/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    volumes:
      - "sailmeilisearch:/data.ms"
    networks:
      - sail
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail
  selenium:
    image: "selenium/standalone-chrome"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - sail
  #  es01:
  #    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
  #    environment:
  #      - node.name=es01
  #      - cluster.name=es-docker-cluster
  #      - discovery.type=single-node
  #      - bootstrap.memory_lock=true
  #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    ulimits:
  #      memlock:
  #        soft: -1
  #        hard: -1
  #    volumes:
  #      - data01:/usr/share/elasticsearch/data
  #    ports:
  #      - 9200:9200
  #      - 9300:9300
  #    networks:
  #      - sail
  #
  #  kib01:
  #    image: docker.elastic.co/kibana/kibana:7.9.3
  #    ports:
  #      - 5601:5601
  #    environment:
  #      ELASTICSEARCH_URL: http://es01:9200
  #      ELASTICSEARCH_HOSTS: http://es01:9200
  #    networks:
  #      - sail
  localstack:
    image: localstack/localstack
    tty: true
    volumes:
      - "saillocalstack:/tmp/localstack"
    ports:
      - "4566:4566"
      - "4571:4571"
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
  sailmeilisearch:
    driver: local
  data01:
    driver: local
  saillocalstack:
    driver: local
